name: 'Branch Testing Backend'

on:
  push:
    branches:
      - '*'
      - '!master'
    paths:
      - 'src/**'
      - '.github/workflows/branches.yml'
      - '.github/actions/build-run-unit-tests/**'

jobs:
  unitTests:
    name: Run unit tests
    runs-on: [ubuntu-latest]
    if: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@main

      - name: Build and run unit tests
        uses: ./.github/actions/build-run-unit-tests
        with:
          workdir: ./src
          project: '*.Unit.Tests/*.csproj'
