name: Build Master

on:
  push:
    branches:
      - 'master'
    paths:
      - 'src/Server/**'
      - '.github/workflows/master.yml'

jobs:
  build-version:
    name: Create project version
    runs-on: [ ubuntu-latest ]
    outputs:
      version: ${{ steps.build-version.outputs.VERSION }}
    steps:
      - name: Set version
        run: echo '::set-output name=VERSION::1.0.1.${{ github.run_number }}'
        id: build-version

  build-identity:
    name: Build Identity
    runs-on: ubuntu-latest
    if: false
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/IdentityServer/IdentityServer.csproj
    - name: Build
      run: dotnet build ./src/IdentityServer/IdentityServer.csproj --configuration Release --no-restore

  build-identity-web:
    name: Build Identity Web
    runs-on: ubuntu-latest
    if: false
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/IdentityServer.Web/IdentityServer.Web.csproj
    - name: Build
      run: dotnet build ./src/IdentityServer.Web/IdentityServer.Web.csproj --configuration Release --no-restore

  functional:
    name: Api functional tests
    runs-on: [ubuntu-latest]
    needs: [ build-identity, build-identity-web ]
    steps:
      - name: Checkout branch
        uses: actions/checkout@main

      - name: Run service dependencies
        run: ./.github/scripts/functional.sh --up

      - name: Check running containers
        run: docker ps -a

      - name: Run functional tests
        run: ./.github/scripts/functional.sh --collection "*collection.json"

      - name: Stop service dependencies
        run: ./.github/scripts/functional.sh --down

  nuget:
    name: Publish package to NuGet
    runs-on: [ubuntu-latest]
    needs: [ build-version ]
    env:
      VERSION: '${{ needs.build-version.outputs.version }}'
    #needs: [ functional ]
    #if: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Create package and publish IdentityServer
        run: ./.github/scripts/nuget.sh --version ${{ env.VERSION }} --dir ./src/Server/IdentityServer --proj IdentityServer.csproj
        env:
          NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}

      - name: Create package and publish IdentityServer.Hosts.Server
        run: ./.github/scripts/nuget.sh --version ${{ env.VERSION }} --dir ./src/Server/Hosts/IdentityServer.Hosts.Server --proj IdentityServer.Hosts.Server.csproj
        env:
          NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}

      - name: Create package and publish IdentityServer.User.Client
        run: ./.github/scripts/nuget.sh --version ${{ env.VERSION }} --dir ./src/Server/IdentityServer.User.Client --proj IdentityServer.User.Client.csproj
        env:
          NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}

#      - name: Add project version change
#        if: ${{ success() }}
#        run: |
#          git add src/Server/IdentityServer/IdentityServer.csproj
#          git add src/Hosts/IdentityServer.Hosts.Server/IdentityServer.Hosts.Server.csproj
#          git add src/Server/IdentityServer.User.Client/IdentityServer.User.Client.csproj
#      - name: Commit files
#        if: ${{ success() }}
#        run: |
#          git config --local user.email "markglibres@gmail.com"
#          git config --local user.name "GitHub Action"
#          git commit -m "bump version" -a
#      - name: Push changes
#        if: ${{ success() }}
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    needs: [ functional ]
    if: false
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout branch
        uses: actions/checkout@main

      - name: Display files
        run: |
          ls -al
          ls -al src
          ls -al src/IdentityServer.Web

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: src/IdentityServer.Web/Dockerfile
          push: true
          tags: bizzpo/identityserver4:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
